#!/bin/bash
#
#	/etc/rc.d/init.d/droonga-http-server
#
#	<A HTTP Protocol Adapter for Droonga>
# chkconfig: 2345 20 80

# Source function library.
. /etc/init.d/functions

NAME=droonga-http-server
DAEMON=/usr/bin/$NAME
export DROONGA_BASE_DIR=/home/$NAME/droonga
PID_FILE=$DROONGA_BASE_DIR/$NAME.pid
DAEMON_ARGS="--daemon --pid-file=$PID_FILE"
export DROONGA_BASE_DIR=/home/$NAME/droonga

[ -x $DAEMON ] || exit 0

start() {
	echo -n "Starting $NAME: "
  daemon $DAEMON $DAEMON_ARGS
  RET_CODE=$?
	touch /var/lock/subsys/$NAME
	return $RET_CODE
}

stop() {
	echo -n "Shutting down $NAME: "
  killproc -p $PID_FILE $DAEMON
  RET_CODE=$?
	rm -f /var/lock/subsys/$NAME
	return $RET_CODE
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
      status $NAME
	;;
    restart)
    	stop
	start
	;;
    *)
	echo "Usage: $NAME {start|stop|status|reload|restart[|probe]"
	exit 1
	;;
esac
exit $?
